# Generated by Django 2.2.6 on 2019-10-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(default=' ', max_length=50)),
                ('last_Name', models.CharField(default=' ', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.PositiveIntegerField(default=1)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
