# Generated by Django 2.2.6 on 2019-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default='0', null=True),
        ),
    ]
