# Generated by Django 2.2.6 on 2019-10-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='number_of_items',
            new_name='number',
        ),
    ]
