# Generated by Django 2.2.6 on 2019-10-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='number',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
