# Generated by Django 2.2.6 on 2019-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20191020_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
