# Generated by Django 2.2.6 on 2019-10-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20191028_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='number',
            new_name='number_of_items',
        ),
    ]
