# Generated by Django 2.2.6 on 2019-11-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20191102_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='cover_the_transaction_fee',
            field=models.BooleanField(default=True),
        ),
    ]
