# Generated by Django 2.2.6 on 2019-10-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_auto_20191028_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='your_donation',
        ),
    ]
