# Generated by Django 2.2.6 on 2019-10-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_remove_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
