# Generated by Django 2.2.6 on 2019-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_donation_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('general', 'general'), ('item1', 'Student Transportation'), ('item2', 'School Materials'), ('item3', 'School Building'), ('item4', 'Medicine')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='donation',
            name='first_Name',
            field=models.CharField(default='first', max_length=50),
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_Name',
            field=models.CharField(default='last', max_length=50),
        ),
    ]
