# Generated by Django 2.2.6 on 2019-10-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_donation_donation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicycle', models.PositiveIntegerField(blank=True, null=True)),
                ('chairs', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
