# Generated by Django 2.2.6 on 2019-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_donationcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcount',
            name='bicycle',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='donationcount',
            name='chairs',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
