# Generated by Django 2.2.6 on 2019-10-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_auto_20191021_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='number',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
