# Generated by Django 2.2.6 on 2019-10-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_auto_20191021_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcount',
            name='general',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
