# Generated by Django 2.2.6 on 2019-10-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0013_auto_20191021_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcount',
            name='general',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
    ]
