# Generated by Django 2.2.6 on 2019-10-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0014_auto_20191021_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=15),
        ),
    ]
