# Generated by Django 2.2.6 on 2019-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0015_auto_20191024_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
