# Generated by Django 2.2.6 on 2019-10-05 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_Name', models.CharField(default=' ', max_length=50)),
                ('last_Name', models.CharField(default=' ', max_length=50)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('number_of_Guests', models.PositiveIntegerField(default=0)),
                ('url_link', models.CharField(default=' ', max_length=200)),
                ('qr_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='qrcodes')),
                ('attended', models.BooleanField(choices=[(True, 'Attended'), (False, 'Absent')], default=False)),
                ('payment_complete', models.BooleanField(choices=[(True, 'Complete'), (False, 'Incomplete')], default=False)),
            ],
        ),
    ]
