# Generated by Django 2.2.6 on 2019-10-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20191007_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='payment_complete',
        ),
    ]
