# Generated by Django 2.2.6 on 2019-10-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_person_payment_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='qr_image',
            field=models.ImageField(default='default.jpg', upload_to='qrcodes'),
        ),
    ]
