# Generated by Django 2.2.6 on 2019-10-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20191017_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='qr_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='qrcodesnew'),
        ),
    ]
