# Generated by Django 2.2.6 on 2019-10-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20191018_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='qr_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='qrcodes'),
        ),
    ]
