# Generated by Django 2.2.6 on 2019-10-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20191018_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='person',
            name='url_link',
        ),
    ]
